# Generated by Django 3.2.9 on 2021-12-08 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('fantype', models.CharField(choices=[('C', 'Casual'), ('S', 'Stan'), ('R', 'Rabid')], default='C', max_length=1)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.quote')),
            ],
        ),
    ]
